env_name: "dev" # 环境名称

server: # 服务配置
  address: "0.0.0.0"
  port: 8000

mysql: # mysql 配置
  host: "127.0.0.1"
  port: 3306
  user: "xxx"
  password: "xxx"
  db_name: rocket
  pool_min_idle: 8 # 最小连接数
  pool_max_open: 32 # 最大连接数
  timeout_seconds: 15 # 连接超时时间单位秒

sqlite: # sqlite 配置
  db_url: "sqlite://data.sqlite3" # Sqlite3 数据库地址
  pool_min_idle: 8 # 最小连接数
  pool_max_open: 32 # 最大连接数
  timeout_seconds: 15 # 连接超时时间单位秒

cors: # cors 跨域配置
  cors_allow_origin: "*"
  cors_allow_methods: "*"
  cors_allow_headers: "*"
